### ISSUE TITLE
how to get scrollbar worked on css of iframe component  when using js like this ?

### ISSUE THREAD

**Issue by frankdevhub** [frankdevhub/frankdevhub.github.io#30]
@MaoJianwei
Hi, Mao~
Thanks for demo you shared on Github 2 years ago, i do really learned much from your ONOS demo, that was really awesome!
Here may i need some help from u ?

The problem is i am now building a personal blog using jekyll  framework.
At the home page i want to post the article which refers to a new online game.

In the post, i  use iframe component to display the official website page of this game.

Problem(Need Help): How to use js script to make the iframe scroll on Y direction to get a better
default view when iframe component is loaded.

Method have tried but not work:

```html
<iframe frameborder="0" id="arma2_iframe" display="block" scrolling="yes" height="400px" id="arma2_official"
	overflow:visible width="100%" src="http://arma2.com" allowFullScreen="true">
</iframe>

<script type="text/javascript">
  $(document).ready(function(){
       var armaIframe = $("#arma2_iframe");
			armaIframe.onload = function(){
			armaIframe.contentWindow.scrollTo(0,500); // i want to get scroll worked but still not working.
		};
  });

</script>
```
Thanks  !

![image](https://user-images.githubusercontent.com/29160332/60697336-51b18580-9f1c-11e9-92a4-0bc643fd27ba.png)

**Comment by jeffslofish** [comment]
Hi, I was just browsing around and saw your issue and thought I could help.... Your iframe has two ids, which is a no-no. Try removing `id="arma2_official"` and see if that helps.

**Comment by frankdevhub** [comment]
@jeffslofish 
Hi,jeffslofish. Thanks for guide. That was a terrible and careless mistake.
However i tried again and still not worked.

I searched and followed the document which appears to work but still achieve nothing.
broswer: chrome

Here is the page i followed:
[the demolink @jsbin.com](https://jsbin.com/gawefuxaya/edit?html,js,output)

Thanks again! 
Franklinfang

![image](https://user-images.githubusercontent.com/29160332/60698037-14e78d80-9f20-11e9-9d44-354ea87dd366.png)

**Comment by jeffslofish** [comment]
I could take a look on my system....what commands do I run to build and run your site using my forked clone?

**Comment by frankdevhub** [comment]
> I could take a look on my system....what commands do I run to build and run your site using my forked clone?

@jeffslofish 
Thanks bro!
My operating sys is windows.
Here is the way to build and run the application:
1.Install Ruby and config path variable.
then check:
```shell
ruby -v
```
2.install Ruby DevKit (Mac may not need t install)
```shell
ruby dk.rb init
ruby dk.rb install
```
3.install jekyll
```shell
gem install jekyll
```
4.fork and run
```shell
jekyll build
jekyll serve
```
- if it starts successfully, u can get to "localhost:4000"
- window sys can run `startup.bat` under demo root to  just run directly.
Wish it may help & Thanks again!

**Comment by jeffslofish** [comment]
Unfortunately, I believe due to cross-origin security policies, this is not possible.

**Comment by frankdevhub** [comment]
like jeffslofish said.
@jeffslofish
